version: "3.9"
services:
  goapp:
    build:
      context: ./build
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/app:rw
    environment:
      # Goモジュールのサポートを有効にする
      GO111MODULE: "on"
      # タグを渡す
      GOFLAGS: "-tags=test"
